//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerAccounting
    {
        public int ID { get; set; }
        public Nullable<int> Server { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> InventoryNumber { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
    
        public virtual EquipmentStatus EquipmentStatus { get; set; }
        public virtual ServerModel ServerModel { get; set; }
    }
}
